import React from 'react';

const AiInsight = ({ analysis }) => {
    if (!analysis) return null;

    return (
        <div className="card border-info bg-light mb-4 shadow-sm">
            <div className="card-header bg-info text-white d-flex align-items-center">
                <i className="bi bi-robot me-2"></i>
                <h5 className="mb-0">Gemini AI Insights</h5>
            </div>
            <div className="card-body">
                <p className="card-text text-dark" style={{ lineHeight: '1.6' }}>
                    {analysis}
                </p>
                <small className="text-muted italic">Generated by AI based on vehicle specs and description.</small>
            </div>
        </div>
    );
};

export default AiInsight;
